name = "GroupIWord2Vec"
uuid = "7a6bfa58-2648-412f-8de3-83cf04c5e4b2"
authors = ["Julian Graupner <Julian.Graupner@physik.hu-berlin.de>", "Pablo Ramos Erpenbeck <p.ramoserpenbeck@campus.tu-berlin.de>", "Knut Bunge <knut.c.bunge@campus.tu-berlin.de>", "Ladislaus Finger <l.finger@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Word2Vec_jll = "9fbe4022-c126-5389-b4b2-756cc9f654d0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"


[compat]
DelimitedFiles = "1.9.1"
LinearAlgebra = "1.10.0"
julia = "1.10"
