name = "GroupIWord2Vec"
uuid = "7a6bfa58-2648-412f-8de3-83cf04c5e4b2"
authors = ["Julian"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DelimitedFiles = "1.9.1"
# Change to Versio "1.10.0" if Julia is version 1.10.0
LinearAlgebra = "1.10.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
