name = "GroupIWord2Vec"
uuid = "7a6bfa58-2648-412f-8de3-83cf04c5e4b2"
authors = ["Julian"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
